const localTypes = {
  // AUTH
  SAVE_USER: "SAVE_USER",
  REMOVE_USER: "REMOVE_USER",
  SAVE_USER_DATA: "SAVE_USER_DATA",
  MAKE_USER_PREMIUM: "MAKE_USER_PREMIUM",

  RESTORE_PURCHASE: "RESTORE_PURCHASE",
  STORE_USER_ID: "STORE_USER_ID",
};

export default localTypes;
